### ISSUE TITLE
TypeError: data type not understood

### ISSUE THREAD

**Issue by bei91** [zhimingluo/UnitBox_TF#3]
Hello,I am trying to run the test file.
But the follow error happens.Could you please help solver this problem? Thanks.
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    model = Model(net_in)
  File "/home/jia/git/UnitBox_TF/UnitBox.py", line 36, in Model
    W_init=tl.layers.deconv2d_bilinear_upsampling_initializer([32, 32, 1, 1]),
  File "/home/jia/tensorflow_env/local/lib/python2.7/site-packages/tensorlayer/layers.py", line 2189, in deconv2d_bilinear_upsampling_initializer
    bilinear_kernel = np.zeros([filter_size, filter_size], dtype=D_TYPE) # dtype=np.float32)
TypeError: data type not understood

**Comment by zhimingluo** [comment]
Hello, I think this issue is because the "tensorlayer" toolbox has update their API, you can check their manual for new API.

**Comment by bei91** [comment]
@zhimingluo 
Thank you for your suggestion that I've solved this problem.

**Comment by zhangpzh** [comment]
Hello ! Have you ever evaluated and compared the performance between IoU loss and that of normal L2 ? Did it really work ?

**Comment by zhimingluo** [comment]
@zhangpzh 
We didn't compare with the normal L2, this repo is just a start code about the implementing of the IoU loss.
Based on this IoU loss, we have a paper about face detection published at the 2018 ICPR, while accuracy still has a large gap between using the anchor-based L1-smooth loss.
And you can also find some papers in 2017 and 2018 CVPR using the IoU loss for text detection.

**Comment by zhangpzh** [comment]
Big thanks !

**Comment by zhangpzh** [comment]
@zhimingluo 
Big thanks !
